marks = []

m1 = int(input("Enter marks here for student 1:"))
marks.append(m1)
m2 = int(input("Enter marks here for student 2:"))
marks.append(m2)
m3 = int(input("Enter marks here for student 3:"))
marks.append(m3)
m4 = int(input("Enter marks here for student 4:"))
marks.append(m4)
m5 = int(input("Enter marks here for student 5:"))
marks.append(m5)
m6 = int(input("Enter marks here for student 6:"))
marks.append(m6)
marks.sort()
print(marks)